# Default callbacks configuration
model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.checkpoint_dir}
  filename: "epoch_{epoch:04d}"
  monitor: "val/auc"
  mode: "max"
  save_last: true
  save_top_k: 1
  auto_insert_metric_name: false

learning_rate_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: "step"

rich_progress_bar:
  _target_: lightning.pytorch.callbacks.RichProgressBar
